### ISSUE TITLE
Merging into existing project

### ISSUE THREAD

**Issue by olszak94** [ixudra/portfolio#1]
Hey there, i was wondering how can i merge portfolio package into my existing project (i'm not an expert-laravel developer). Is it easy and doable by newbie ?

**Comment by elimentz** [comment]
Hey! If you follow the instructions as mentioned in the readme, you should be able to get the package to work in your project. That said, since you are working with an existing website I can imagine that you want to keep the look and feel identical to what you  already have. This is also possible, but it might require more customization on your part. None of this is particularly complicated, but might need some advanced Laravel knowledge, depending on what you want to achieve.

I'm sorry that I haven't gotten around to extending the documentation. If you're up for it, I would be more than happy to guide you through it and get some feedback on how I can improve the package and the documentation :-)

**Comment by olszak94** [comment]
Alright, i'll try to get it working soon, if i success i will for sure contact you again.

Btw, i followed [this](http://laravelcoding.com/blog/laravel-5-beauty-introduction?tag=L5+Beauty) nice tutorial series for blog platform powered by laravel.

Thank you for you quick response!

**Comment by olszak94** [comment]
I did as stated in readme, and when i try to access http://www.example.org/admin/customers/create it throws this error

![error](http://i.imgur.com/3FmNHP8.png)

I can't find models directory at all.

**Comment by elimentz** [comment]
hey, it seems I made a mistake in the bindings config file: `models` should be changed to `Models` to make it work. Either publish the config files and change them yourself or pull in the latest version of the package, which has a fix :-)

**Comment by olszak94** [comment]
The other thing i bumped into is

```
Class Ixudra\Interfaces\Portfolio\Services\Html\ProjectTypeViewFactoryInterface does not exist
```

**Comment by elimentz** [comment]
The fix is quite simple: this should be changed to `Ixudra\Portfolio\Interfaces\Services\Html\ProjectTypeViewFactoryInterface` but I can't seem to find where it occurs. Can you tell me in which file you encounter the problem?

**Comment by olszak94** [comment]
```
<url>/admin/projectTypes
<url>/admin/people
```

after the change, it still show up

```
 Class Ixudra\Portfolio\Interfaces\Services\Html\ProjectTypeViewFactoryInterface does not exist
```

But it exists...

After i access `<url>/admin/people` it shows 

```
Interface 'Ixudra\Portfolio\Interfaces\Http\Controllers\PersonControllerInterface' not found
```

And this one, doesn't exist.

**Comment by elimentz** [comment]
the `/admin/people` route has not been finished yet, so there are still a couple of bugs in there that I'm aware of. I'll try to finish that this evening. The `admin/projectTypes` should work though, I use that on my website as well and it works perfectly. Is it possible that you are using an old version of the package? Because I fixed that bug in version [0.0.9](https://github.com/ixudra/portfolio/commit/e4d97670685489970ebdb24e3d16bd6960d77464). If you update to version 0.0.10, it should work fine.

What version of the package are you using?

**Comment by olszak94** [comment]
Updated to 0.0.10 and `admin/projectTypes` works fine now.

Whenever i try to add new project at `<url>/admin/projects/create`, it says that `The file field is required.` even if i choose a file, should it be an image?

**Comment by elimentz** [comment]
the allowed mime types are `jpg`, `jpeg` and `png`, though you should get a notification if you don't use one of these mime types. I'll put that on my checklist. Can you check the size of the file? I do know of a PHP issue where you get this particular error message if the file is larger than the maximum file size allowed by your PHP server (in my case 2MB). As far as I know, there is no way I can fix that in the package. Try uploading a small image and see if that works - it should ;-)

**Comment by olszak94** [comment]
That works, with smaller image. How about displaying results on public page? How to do this ?

**Comment by olszak94** [comment]
That works just fine, with small image.

How about displaying projects and stuff in public page ?

**Comment by elimentz** [comment]
I assume you mean show the project information to all users, not just admins? 

What I typically do is separate the `/admin/projects` and `/projects` urls with different controllers - makes things more readable and reduces the amount of permission checks. So I would create a `App\Http\Controllers\ProjectController` where I would recover the project(s) from the database and pass them along to the view. But there really are no rules here, you can do this however you wish. You can see how I display all the data by browsing through the package files:
- [controller](https://github.com/ixudra/portfolio/blob/master/src/Ixudra/Portfolio/Http/Controllers/ProjectController.php)
- [view factory](https://github.com/ixudra/portfolio/blob/master/src/Ixudra/Portfolio/Services/Html/ProjectViewFactory.php)
- [view](https://github.com/ixudra/portfolio/blob/master/src/resources/views/projects/show.blade.php)

But again: this is how I like to do this, you can do it how ever you like :)

**Comment by olszak94** [comment]
Alright, that ticket helped me alot ^_^ it's good "tutorial" to use this package into existing project.

**Comment by elimentz** [comment]
Happy to hear that! Let me know if there is any additional feedback you might have on how the package can be improved.
